{% set name = "polars-upgrade" %}
{% set version = "0.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polars_upgrade-{{ version }}.tar.gz
  sha256: 0f91859f8abb17e1b7ef5803e2e277056d48648c29f045821db4ae5fc52ab614

build:
  entry_points:
    - polars-upgrade = polars_upgrade._main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - tokenize-rt >=5.2.0

test:
  imports:
    - polars_upgrade
  commands:
    - pip check
    - polars-upgrade --help
  requires:
    - pip

about:
  home: https://github.com/MarcoGorelli/polars-upgrade
  summary: Automatically upgrade your Polars code so it's compatible with future versions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - '0xbe7a'
